var annotated_dup =
[
    [ "Signal", "namespaceSignal.html", "namespaceSignal" ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "utils", "namespaceutils.html", "namespaceutils" ],
    [ "_sprite_highlight_color_t", "class__sprite__highlight__color__t.html", "class__sprite__highlight__color__t" ],
    [ "AudioConfig", "structAudioConfig.html", "structAudioConfig" ],
    [ "AudioError", "classAudioError.html", null ],
    [ "AudioMixer", "classAudioMixer.html", "classAudioMixer" ],
    [ "AudioMusicVolumeChangeEvent", "structAudioMusicVolumeChangeEvent.html", "structAudioMusicVolumeChangeEvent" ],
    [ "AudioPlay3DEvent", "structAudioPlay3DEvent.html", "structAudioPlay3DEvent" ],
    [ "AudioPlayEvent", "structAudioPlayEvent.html", "structAudioPlayEvent" ],
    [ "AudioPruneEvent", "structAudioPruneEvent.html", null ],
    [ "AudioSetMutedEvent", "structAudioSetMutedEvent.html", "structAudioSetMutedEvent" ],
    [ "AudioSoundVolumeChangeEvent", "structAudioSoundVolumeChangeEvent.html", "structAudioSoundVolumeChangeEvent" ],
    [ "AudioStopEvent", "structAudioStopEvent.html", null ],
    [ "AudioTrigger3DEvent", "structAudioTrigger3DEvent.html", "structAudioTrigger3DEvent" ],
    [ "AudioTriggerEvent", "structAudioTriggerEvent.html", "structAudioTriggerEvent" ],
    [ "Bar", "classBar.html", "classBar" ],
    [ "BiomeData", "structBiomeData.html", "structBiomeData" ],
    [ "Button", "classButton.html", "classButton" ],
    [ "ButtonGroup", "classButtonGroup.html", "classButtonGroup" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "Checkbox", "classCheckbox.html", "classCheckbox" ],
    [ "ComboBox", "classComboBox.html", "classComboBox" ],
    [ "CompressionError", "classCompressionError.html", null ],
    [ "ConfigurationError", "classConfigurationError.html", null ],
    [ "Constant", "structConstant.html", null ],
    [ "Coordinate3D", "structCoordinate3D.html", "structCoordinate3D" ],
    [ "CytopiaError", "classCytopiaError.html", null ],
    [ "DisplayError", "classDisplayError.html", null ],
    [ "Engine", "classEngine.html", "classEngine" ],
    [ "EventManager", "classEventManager.html", "classEventManager" ],
    [ "FontError", "classFontError.html", null ],
    [ "Frame", "classFrame.html", "classFrame" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GameClock", "classGameClock.html", "classGameClock" ],
    [ "GameLoopMQ", "classGameLoopMQ.html", null ],
    [ "GameService", "classGameService.html", "classGameService" ],
    [ "GameStates", "classGameStates.html", "classGameStates" ],
    [ "GameStatesData", "structGameStatesData.html", "structGameStatesData" ],
    [ "GetMemberType", "structGetMemberType.html", null ],
    [ "GetMemberType< Member Type::* >", "structGetMemberType_3_01Member_01Type_1_1_5_01_4.html", "structGetMemberType_3_01Member_01Type_1_1_5_01_4" ],
    [ "GetType", "structGetType.html", null ],
    [ "GetType_t", "structGetType__t.html", "structGetType__t" ],
    [ "GetType_t< i, List< T, Ts... >, EnableIf< i==0 > >", "structGetType__t_3_01i_00_01List_3_01T_00_01Ts_8_8_8_01_4_00_01EnableIf_3_01i_0A_0A0_01_4_01_4.html", "structGetType__t_3_01i_00_01List_3_01T_00_01Ts_8_8_8_01_4_00_01EnableIf_3_01i_0A_0A0_01_4_01_4" ],
    [ "GetType_t< i, List< T1, T2, Ts... >, EnableIf< i !=0 > >", "structGetType__t_3_01i_00_01List_3_01T1_00_01T2_00_01Ts_8_8_8_01_4_00_01EnableIf_3_01i_01_9_0A0_01_4_01_4.html", "structGetType__t_3_01i_00_01List_3_01T1_00_01T2_00_01Ts_8_8_8_01_4_00_01EnableIf_3_01i_01_9_0A0_01_4_01_4" ],
    [ "IEquatable", "classIEquatable.html", "classIEquatable" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "IMenuGroup", "classIMenuGroup.html", "classIMenuGroup" ],
    [ "is_strong_equatable_type", "structis__strong__equatable__type.html", null ],
    [ "is_strong_equatable_type< Type, std::void_t< decltype(std::declval< Type >().Equals(std::declval< Type >()))> >", "structis__strong__equatable__type_3_01Type_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_045bb826f487fd03476268e6182009f23.html", null ],
    [ "Layout", "classLayout.html", "classLayout" ],
    [ "LayoutData", "structLayoutData.html", "structLayoutData" ],
    [ "LayoutGroup", "structLayoutGroup.html", "structLayoutGroup" ],
    [ "LOG", "classLOG.html", "classLOG" ],
    [ "Map", "classMap.html", "classMap" ],
    [ "MapLayers", "classMapLayers.html", "classMapLayers" ],
    [ "MapNode", "classMapNode.html", "classMapNode" ],
    [ "MapNodeData", "structMapNodeData.html", "structMapNodeData" ],
    [ "MessageQueue", "classMessageQueue.html", "classMessageQueue" ],
    [ "Observer", "classObserver.html", "classObserver" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "Randomizer", "classRandomizer.html", "classRandomizer" ],
    [ "RequiredTilesData", "structRequiredTilesData.html", "structRequiredTilesData" ],
    [ "ResourceManager", "classResourceManager.html", "classResourceManager" ],
    [ "ResourcesManager", "classResourcesManager.html", "classResourcesManager" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "SettingsData", "structSettingsData.html", "structSettingsData" ],
    [ "Singleton", "classSingleton.html", "classSingleton" ],
    [ "Slider", "classSlider.html", "classSlider" ],
    [ "Soundtrack", "structSoundtrack.html", "structSoundtrack" ],
    [ "Sprite", "classSprite.html", "classSprite" ],
    [ "SpriteData", "structSpriteData.html", "structSpriteData" ],
    [ "SpriteRGBColor", "structSpriteRGBColor.html", "structSpriteRGBColor" ],
    [ "StrongType", "structStrongType.html", "structStrongType" ],
    [ "Subject", "classSubject.html", "classSubject" ],
    [ "TerminateEvent", "structTerminateEvent.html", null ],
    [ "TerrainGenerator", "classTerrainGenerator.html", "classTerrainGenerator" ],
    [ "TerrainSettings", "structTerrainSettings.html", "structTerrainSettings" ],
    [ "Text", "classText.html", "classText" ],
    [ "TextField", "classTextField.html", "classTextField" ],
    [ "TileData", "structTileData.html", "structTileData" ],
    [ "TileManager", "classTileManager.html", "classTileManager" ],
    [ "TileSetData", "structTileSetData.html", "structTileSetData" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Tooltip", "classTooltip.html", "classTooltip" ],
    [ "Transition", "structTransition.html", "structTransition" ],
    [ "TransitiveModel", "classTransitiveModel.html", "classTransitiveModel" ],
    [ "TupleType", "structTupleType.html", null ],
    [ "TupleType< List< Ts... > >", "structTupleType_3_01List_3_01Ts_8_8_8_01_4_01_4.html", "structTupleType_3_01List_3_01Ts_8_8_8_01_4_01_4" ],
    [ "TypeList", "structTypeList.html", null ],
    [ "TypeList< T >", "structTypeList_3_01T_01_4.html", "structTypeList_3_01T_01_4" ],
    [ "TypeList< T, Ts... >", "structTypeList_3_01T_00_01Ts_8_8_8_01_4.html", "structTypeList_3_01T_00_01Ts_8_8_8_01_4" ],
    [ "UIChangeEvent", "structUIChangeEvent.html", "structUIChangeEvent" ],
    [ "UIElement", "classUIElement.html", "classUIElement" ],
    [ "UIError", "classUIError.html", null ],
    [ "UILoopMQ", "classUILoopMQ.html", null ],
    [ "UIManager", "classUIManager.html", "classUIManager" ],
    [ "UnimplementedError", "classUnimplementedError.html", null ],
    [ "VariantType", "structVariantType.html", null ],
    [ "VariantType< List< Ts... > >", "structVariantType_3_01List_3_01Ts_8_8_8_01_4_01_4.html", "structVariantType_3_01List_3_01Ts_8_8_8_01_4_01_4" ],
    [ "WindowManager", "classWindowManager.html", "classWindowManager" ],
    [ "WindowResizeEvent", "structWindowResizeEvent.html", null ]
];